name: example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  # flutter_riverpod: ^2.4.9
  snowflake_route: 
    path: ..
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  toastification: ^1.2.0
  # riverpod: ^2.4.1
  # riverpod_annotation: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/home/
    - assets/value_based/
    - assets/guard/