name: hyper_router
description: Declarative, type-safe, codegen-free router for flutter. Optional URL support. Highly extensible.
version: 0.0.7
repository: https://github.com/sufftea/hyper_router

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  provider: ^6.1.2

topics:
  - navigation
  - router
